# Generated by Django 5.2.4 on 2025-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('checkup_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_checkup', models.DateField()),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('umur', models.IntegerField(blank=True, null=True)),
                ('tinggi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('berat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lingkar_perut', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gestational_diabetes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gula_darah_puasa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gula_darah_sewaktu', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('asam_urat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tekanan_darah', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=100, null=True)),
                ('derajat_kesehatan', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'checkups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('jabatan', models.TextField()),
                ('lokasi', models.TextField()),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('tanggal_MCU', models.DateField(blank=True, null=True)),
                ('expired_MCU', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('upload_batch_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'karyawan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('nama', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lokasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
