# Generated by Django 5.2.7 on 2025-11-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekomendasiKesehatan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=100)),
                ('rekomendasi_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('karyawan_uid', models.ForeignKey(db_column='karyawan_uid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
            options={
                'db_table': 'rekomendasi_kesehatan',
                'managed': True,
            },
        ),
    ]
